# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:            Atomic
title_tag:        Lambda
tagline:          'A Jekyll theme'
description:      'This is my attempt of trying to document my experience in software.'
url:              http://hyde.getpoole.com
baseurl:          /AtomicLambda/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

gems: [jekyll-paginate, jekyll-gist]
paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
